name: xpense
description: An easy-to-use expense tracker mobile application with beautiful user interface..

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
    sdk: ">=2.17.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    provider: ^6.0.3
    sqflite: ^2.0.3
    path_provider: ^2.0.11
    path: ^1.8.1
    shared_preferences: ^2.0.15

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
